# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 10
  - name: 文档
    url: /docs/
    weight: 20
  - name: GitHub
    url: https://github.com/ourongbin/financial-manager
    weight: 30
